#!/usr/bin/env bash
# Script de lancement Analyst5
SCRIPT="$(readlink -f "${BASH_SOURCE[0]}")"
DIR="$(cd "$(dirname "$SCRIPT")" && pwd)"
source "$DIR/venv/bin/activate"
python "$DIR/analyst5.py" "$@"
